//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRIBUTO
    {
        public ATRIBUTO()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int ID { get; set; }
        public string TIPO { get; set; }
        public string STRING { get; set; }
        public byte[] ARCHIVO { get; set; }
        public Nullable<float> FLOAT { get; set; }
        public Nullable<int> INT { get; set; }
        public string NOMBRE { get; set; }
        public string PRODUCTOID { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
