//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRIBUTO
    {
        public ATRIBUTO()
        {
            this.PRODUCTO_ATRIBUTO = new HashSet<PRODUCTO_ATRIBUTO>();
        }
    
        public int ID { get; set; }
        public string TIPO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<PRODUCTO_ATRIBUTO> PRODUCTO_ATRIBUTO { get; set; }
    }
}
