//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public int ID { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public byte[] thumbnail { get; set; }
    }
}
