//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODRELACIONADOS
    {
        public PRODRELACIONADOS()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public string PROD1 { get; set; }
        public string PROD2 { get; set; }
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
