//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_ATRIBUTO
    {
        public int id_producto { get; set; }
        public int id_atributo { get; set; }
        public string valor { get; set; }
    
        public virtual ATRIBUTO ATRIBUTO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
