//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACION
    {
        public int ID { get; set; }
        public Nullable<int> ProductoIzq { get; set; }
        public Nullable<int> ProductoDer { get; set; }
        public string Nombre { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PRODUCTO PRODUCTO1 { get; set; }
    }
}
