//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRIBUTO
    {
        public int ID { get; set; }
        public string Resumen { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] IMAGEN { get; set; }
        public Nullable<float> PRECIO { get; set; }
        public string PRODUCTOID { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
