//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRIBUTO
    {
        public ATRIBUTO()
        {
            this.ATRIBUTO1 = new HashSet<ATRIBUTO>();
            this.ATRIBUTO2 = new HashSet<ATRIBUTO>();
        }
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public int TIPO { get; set; }

        public virtual ICollection<ATRIBUTO> ATRIBUTO1 { get; set; }
        public virtual ICollection<ATRIBUTO> ATRIBUTO2 { get; set; }
        public virtual TIPO_ATRIBUTO TIPO_ATRIBUTO { get; set; }
        public virtual TIPO_ATRIBUTO TIPO_ATRIBUTO1 { get; set; }
    }
}
