//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plytix
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ATRIBUTO
    {
        public TIPO_ATRIBUTO()
        {
            this.ATRIBUTO1 = new HashSet<ATRIBUTO>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ATRIBUTO ATRIBUTO { get; set; }
        public virtual ICollection<ATRIBUTO> ATRIBUTO1 { get; set; }
    }
}
